# Generated by Django 4.2.1 on 2023-06-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('telefono', models.CharField(max_length=15)),
                ('mensaje', models.CharField(max_length=1000)),
            ],
        ),
    ]
