# Generated by Django 4.2.1 on 2023-06-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulariocontacto',
            options={'permissions': [('puede_leer_formulario', 'Permiso para lectura de formularios')]},
        ),
    ]
